# Generated by Django 6.0.3 on 2026-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nome_evento',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
